// Seed script — Toronto Pearson Taxi Tariffs (February 2024)
// Run: node scripts/seedSedanRates.js

const { MongoClient } = require("mongodb");

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017";
const DB_NAME = process.env.MONGODB_DB || "transportbooking";

const SEDAN_RATES = [
  { destination: "Aldershot", tariff: 115 },
  { destination: "Alliston", tariff: 153 },
  { destination: "Alton", tariff: 115 },
  { destination: "Ancaster", tariff: 133 },
  { destination: "Angus", tariff: 186 },
  { destination: "Arthur", tariff: 186 },
  { destination: "Aurora", tariff: 104 },
  { destination: "Ballantrae", tariff: 124 },
  { destination: "Barrie", tariff: 177 },
  { destination: "Beamsville", tariff: 173 },
  { destination: "Beaverton", tariff: 235 },
  { destination: "Beeton", tariff: 133 },
  { destination: "Belleville", tariff: 377 },
  { destination: "Bolton", tariff: 75 },
  { destination: "Bond Head", tariff: 118 },
  { destination: "Bowmanville", tariff: 164 },
  { destination: "Bracebridge", tariff: 347 },
  { destination: "Bradford", tariff: 122 },
  { destination: "Brantford", tariff: 193 },
  { destination: "Brockville", tariff: 672 },
  { destination: "Brooklin", tariff: 140 },
  { destination: "Borougham", tariff: 108 },
  { destination: "Buffalo", tariff: 314 },
  { destination: "Buffalo Airport", tariff: 314 },
  { destination: "Burford", tariff: 208 },
  { destination: "Caledon", tariff: 100 },
  { destination: "Caledon East", tariff: 92 },
  { destination: "Caledonia", tariff: 175 },
  { destination: "Cambridge", tariff: 158 },
  { destination: "Camp Borden", tariff: 187 },
  { destination: "Campbellville", tariff: 100 },
  { destination: "Carlisle", tariff: 118 },
  { destination: "Cedar Mills", tariff: 87 },
  { destination: "Cheltenham", tariff: 91 },
  { destination: "Claremont", tariff: 121 },
  { destination: "Cobourg", tariff: 254 },
  { destination: "Collingwood", tariff: 265 },
  { destination: "Cookstown", tariff: 139 },
  { destination: "Courtice", tariff: 159 },
  { destination: "Creemore", tariff: 193 },
  { destination: "Deerhurst", tariff: 427 },
  { destination: "Delhi", tariff: 285 },
  { destination: "Detroit", tariff: 696 },
  { destination: "Douglas Point", tariff: 417 },
  { destination: "Dundas", tariff: 130 },
  { destination: "Durham", tariff: 284 },
  { destination: "Elmira", tariff: 208 },
  { destination: "Elora", tariff: 189 },
  { destination: "Ennismore", tariff: 309 },
  { destination: "Erin", tariff: 121 },
  { destination: "Fenelon Falls", tariff: 305 },
  { destination: "Fergus", tariff: 175 },
  { destination: "Flamboro Centre", tariff: 124 },
  { destination: "Flamborough", tariff: 124 },
  { destination: "Flesherton", tariff: 237 },
  { destination: "Fort Erie", tariff: 293 },
  { destination: "Freelton", tariff: 125 },
  { destination: "Galt", tariff: 158 },
  { destination: "Georgetown", tariff: 86 },
  { destination: "Goderich", tariff: 393 },
  { destination: "Goodwood", tariff: 133 },
  { destination: "Gormley", tariff: 95 },
  { destination: "Grand Valley", tariff: 162 },
  { destination: "Gravenhurst", tariff: 315 },
  { destination: "Grimsby", tariff: 155 },
  { destination: "Guelph", tariff: 147 },
  { destination: "Hagersville", tariff: 217 },
  { destination: "Hamilton - DT", tariff: 128 },
  { destination: "Hamilton - MTN", tariff: 140 },
  { destination: "Hanover", tariff: 338 },
  { destination: "Holland Landing", tariff: 127 },
  { destination: "Horseshoe Valley", tariff: 210 },
  { destination: "Huntsville", tariff: 412 },
  { destination: "Ingersoll", tariff: 270 },
  { destination: "Inglewood", tariff: 100 },
  { destination: "Jarvis", tariff: 238 },
  { destination: "Jacksons Point", tariff: 186 },
  { destination: "Keswick", tariff: 163 },
  { destination: "Kettleby", tariff: 93 },
  { destination: "Kilbride", tariff: 113 },
  { destination: "Kimberley", tariff: 273 },
  { destination: "King City", tariff: 84 },
  { destination: "Kingston", tariff: 531 },
  { destination: "Kitchener", tariff: 177 },
  { destination: "Lindsay", tariff: 276 },
  { destination: "London", tariff: 338 },
  { destination: "Loretto", tariff: 107 },
  { destination: "Midland", tariff: 273 },
  { destination: "Mohawk Raceway", tariff: 100 },
  { destination: "Mono Mills", tariff: 100 },
  { destination: "Montreal", tariff: 1093 },
  { destination: "Mt. Hope Airport", tariff: 158 },
  { destination: "Newcastle", tariff: 184 },
  { destination: "Newmarket", tariff: 113 },
  { destination: "Niagara Falls, ON", tariff: 239 },
  { destination: "Niagara on the Lake", tariff: 252 },
  { destination: "Nobleton", tariff: 76 },
  { destination: "North Bay", tariff: 690 },
  { destination: "Norval", tariff: 75 },
  { destination: "Orangeville", tariff: 128 },
  { destination: "Orillia", tariff: 247 },
  { destination: "Ottawa", tariff: 863 },
  { destination: "Palgrave", tariff: 93 },
  { destination: "Paris", tariff: 208 },
  { destination: "Parry Sound", tariff: 421 },
  { destination: "Peterborough", tariff: 279 },
  { destination: "Port Colborne", tariff: 279 },
  { destination: "Port Hope", tariff: 225 },
  { destination: "Port Perry", tariff: 177 },
  { destination: "Quebec City", tariff: 1495 },
  { destination: "Rockwood", tariff: 123 },
  { destination: "Schomberg", tariff: 100 },
  { destination: "Sharon", tariff: 124 },
  { destination: "Shelburne", tariff: 163 },
  { destination: "St. Catharines", tariff: 208 },
  { destination: "St. Jacobs", tariff: 190 },
  { destination: "St. Thomas", tariff: 351 },
  { destination: "Stoney Creek", tariff: 133 },
  { destination: "Stouffville", tariff: 115 },
  { destination: "Stratford", tariff: 254 },
  { destination: "Sudbury", tariff: 736 },
  { destination: "Sutton", tariff: 177 },
  { destination: "Talisman", tariff: 266 },
  { destination: "Terra Cotta", tariff: 93 },
  { destination: "Thorold", tariff: 221 },
  { destination: "Tottenham", tariff: 107 },
  { destination: "Trenton", tariff: 352 },
  { destination: "Uxbridge", tariff: 152 },
  { destination: "Wasaga Beach", tariff: 245 },
  { destination: "Waterdown", tariff: 115 },
  { destination: "Waterloo", tariff: 190 },
  { destination: "Welland", tariff: 252 },
  { destination: "Windsor", tariff: 683 },
  { destination: "Woodstock", tariff: 240 },
];

async function main() {
  const client = new MongoClient(MONGODB_URI);
  try {
    await client.connect();
    const db = client.db(DB_NAME);
    const col = db.collection("rates");

    const docs = SEDAN_RATES.map(({ destination, tariff }) => ({
      destination,
      tariff,
      carType: "Sedan",
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    const result = await col.insertMany(docs, { ordered: false });
    console.log(`✅ Inserted ${result.insertedCount} Sedan rate records.`);
  } finally {
    await client.close();
  }
}

main().catch((err) => {
  console.error("❌ Seed failed:", err.message);
  process.exit(1);
});
